server:
  port: 8502

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_service
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
---

spring:
  application:
    name: ticket-service

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/